#!/bin/sh

zestty_picker() {
    query=${1:-}
    shift

    fzf --query="$query" \
        --delimiter="$ZESTTY_DELIM" \
        --info=hidden \
        --no-separator \
        --no-multi \
        --select-1 \
        --cycle \
        --height=7 \
        --layout=reverse \
        --color=fg:#c0caf5 \
        --color=fg+:#c0caf5 \
        --color=bg+:#383e5a \
        --color=prompt:#7aa2f7 \
        --color=header:#7aa2f7 \
        --color=gutter:-1 \
        --color=pointer:#7aa2f7 \
        --color=hl:#e25c74 \
        --color=hl+:#e25c74 \
        "$@"
}

command=${1:-}
query=${2:-}

case "$command" in
    "zellij" | "active" | "dead" | "projects" | "submodules")
        selected=$(
            zestty list "--$command" |
            zestty_picker "$query" --header="$command" --with-nth="2"
        )
        ;;
    "worktrees")
        selected=$(
            zestty list --worktrees |
            zestty_picker "$query" --header="worktrees" \
                --with-nth="{3}$ZESTTY_DELIM({2})" --nth "1"
        )
        ;;
esac

[ -n "$selected" ] && zestty sessionize "$selected"
